//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCompetitions.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accident_People
    {
        public int ID { get; set; }
        public Nullable<int> ID_people { get; set; }
        public Nullable<int> ID_accident { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Accident Accident { get; set; }
        public virtual People People { get; set; }
    }
}
