//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCompetitions.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achivments
    {
        public int ID { get; set; }
        public Nullable<int> ID_People { get; set; }
        public Nullable<int> ID_Competition_Participant { get; set; }
        public Nullable<int> ID_Medal { get; set; }
    
        public virtual Competition_Participant Competition_Participant { get; set; }
        public virtual Medal Medal { get; set; }
        public virtual People People { get; set; }
    }
}
