//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCompetitions.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coach
    {
        public int ID { get; set; }
        public Nullable<int> ID_People { get; set; }
        public Nullable<int> ID_Coach { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual People People { get; set; }
    }
}
