//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportCompetitions.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition_Participant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competition_Participant()
        {
            this.Achivments = new HashSet<Achivments>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Team { get; set; }
        public Nullable<int> ID_People { get; set; }
        public Nullable<int> ID_Competition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Achivments> Achivments { get; set; }
        public virtual Competition Competition { get; set; }
        public virtual People People { get; set; }
        public virtual Team Team { get; set; }
    }
}
