//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Materialy.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy_Details
    {
        public int Id { get; set; }
        public Nullable<int> Id_Materials { get; set; }
        public Nullable<int> Id_Buy { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<double> Cost { get; set; }
    
        public virtual Buy Buy { get; set; }
        public virtual Materials Materials { get; set; }
    }
}
