//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Materialy.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int Id { get; set; }
        public Nullable<int> Id_Provider { get; set; }
        public Nullable<int> Id_Materials { get; set; }
        public Nullable<int> Id_Unit { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> Count1 { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
