//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupAndSonger.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class buy_tick
    {
        public int ID { get; set; }
        public Nullable<int> ID_Tour { get; set; }
        public Nullable<int> ID_Place { get; set; }
        public Nullable<System.DateTime> Date_beg { get; set; }
        public Nullable<System.DateTime> Date_ov { get; set; }
        public Nullable<int> SummPR_tick { get; set; }
        public Nullable<int> Price_tick { get; set; }
        public Nullable<int> Count_tick { get; set; }
    
        public virtual places places { get; set; }
        public virtual tours tours { get; set; }
    }
}
