//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupAndSonger.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour_songs
    {
        public int ID { get; set; }
        public Nullable<int> ID_Tour { get; set; }
        public Nullable<int> ID_Song { get; set; }
    
        public virtual songs songs { get; set; }
        public virtual tours tours { get; set; }
    }
}
